### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by jiqinga** [moreKing/web-firewall#1]
![image](https://github.com/user-attachments/assets/37469246-8c01-45f1-b7f8-1035c92feca7)
 系统版本： CentOS Linux release 7.9.2009 (Core)

**Comment by moreKing** [comment]
你好，谢谢你的反馈，由于本系统是建立的nftables的基础上，所以没有考虑到centos7的环境，是准备在后面支持iptables的时候进行支持的，我大概在本周五的时候发布一个新版本，到时候先支持在centos7上运行，但是需要你在centos7上执行 `yum install nftables` 来额外安装一些依赖，并且不保证还会有其他的问题，我准备将nftables功能开发完备后，紧接着下一步对iptables系统进行支持

**Comment by jiqinga** [comment]
系统中是有nftables的，但GLIBC最高版本是GLIBC_2.18，可以手动编译升级，但可能会其他问题，能支持iptables是最好的了

**Comment by moreKing** [comment]
好的 GLIBC的问题不用担心，我这边编译环境降低就可以了，高的可以兼容低的环境，那么下个版本可以尝试使用一下，预计就这几天会发布

**Comment by jiqinga** [comment]
![image](https://github.com/user-attachments/assets/2f4b03f5-86b2-48ff-916c-3358c779cbb6)

哦哦好的，还有个问题就是目前web-firewalld.service没有设置重启间隔，如果启动失败会不断重启可能导致系统资源被迅速消耗(start request repeated too quickly for web-firewalld.service),默认间隔似乎是0.1s，可以加上RestartSec参数设置服务重启的时间间隔

**Comment by moreKing** [comment]
好的 这块我也加入到service文件中

**Comment by moreKing** [comment]
我测试了一下，centos7打包是正常的，但是centos上nft命令不能创建nat链，我的新版本支持转发流量以及地址转换，导致不能再centos上进行使用，可能还是等得适配iptables才好用了

**Comment by jiqinga** [comment]
![image](https://github.com/user-attachments/assets/be26b1d1-bca3-4ba9-afbc-f532d2b15400)
我在debian12试用了下新版本，发现以下问题:
- 系统管理里的shell直接报错
- 当我重启nft `systemctl restart nftables.service`后，策略会被清空，此时在web页面上操作策略会直接报错，重复web-firewall服务后会恢复正常
- 使用目的地址转换功能不生效，后面找到原因是没开启路由转发，大多数linux系统是默认关闭路由转发的，时候考虑使用此功能时自动开启路由转发
- 使用目的地址转换功能如果不在源地址转换那里配置允许目的ip也是不成功的，个人觉得配置了目的地址转换还需要在源地址转换那里配置允许目的ip似乎有些复杂了

**Comment by moreKing** [comment]
1. 我来测试一下
2. 这个没有考虑到用户还会直接操作nftables，下个版本修复
3. 版本发布的时候我出了视频里面有这块的说明
4. 目的地址为什么让用户填写，举个例子，用户有多个公网ip，如果只希望其中一个公网ip做映射，那么就填写这个目标地址，处于这样的方式考虑，视频也有说明，请参考下面视频

https://www.bilibili.com/video/BV1XB4WeEECx/#reply242079437232
