### ISSUE TITLE
修改访问端口

### ISSUE THREAD

**Issue by shuiqingwuyv** [moreKing/web-firewall#6]
你好 请问能否增加一个安装时候修改访问端口的功能呢 我机器本身8000端口已经使用且没法修改了呢

**Comment by moreKing** [comment]
安装完成后可以修改配置文件，具体可以参考配置文件的文档，改完之后就按照修改后的端口启动，并自动打开防火墙对应端口

**Comment by moreKing** [comment]
https://moujun.top/web-firewall/config.html 具体可以参考这个链接
