### ISSUE TITLE
针对原有nft规则如何处理？

### ISSUE THREAD

**Issue by Tychoxs** [moreKing/web-firewall#7]
本地已经通过nftables配置了相关的防火墙策略，安装后，是会自动提取转化？还是默认覆盖？

**Comment by moreKing** [comment]
不处理 nftables可以创建新的表跟链，只是根据优先级来进行先后的策略判定

**Comment by moreKing** [comment]
原有的策略依然生效，只是某些策略可能会因为优先级的问题导致策略冲突不生效了，所以建议关闭其他的策略，在配置文件中可以对链的优先级进行修改来一定程度上缓解这个问题，最好还是不要在多个防火墙软件中创建策略

**Comment by gracelsy** [comment]
我在openwrt上安装web-firewalld
默认策略未生效，上不了网

请问下如何调整优先级，来进行先后的策略判定
